Repository FlexMeasures/flexmeasures, pull requests merged in 2021-09, with the labels that each got.

#167 Fix bug for Flask AnonymousUser not having an account associated with it
  flexmeasures/utils/app_utils.py
Labels: bug

#168 Let sensor API check for ownership of the corresponding GenericAsset
  flexmeasures/api/dev/sensors.py
Labels: API, security

#166 Customize view titles and icons
  Makefile
  documentation/conf.py
  documentation/configuration.rst
  flexmeasures/ui/__init__.py
  flexmeasures/ui/templates/defaults.jinja
  flexmeasures/utils/config_defaults.py
Labels: UI, Plugin support

#163 [UI] Add configurability to the menu, what root view to show and what name to use
  Makefile
  ci/run_mypy.sh
  documentation/changelog.rst
  documentation/conf.py
  documentation/configuration.rst
  flexmeasures/app.py
  flexmeasures/data/migrations/versions/96f2db5bed30_add_account_roles.py
  flexmeasures/data/models/user.py
  flexmeasures/data/scripts/cli_tasks/data_add.py
  flexmeasures/data/scripts/cli_tasks/data_delete.py
  flexmeasures/ui/__init__.py
  flexmeasures/ui/templates/defaults.jinja
  flexmeasures/ui/views/dashboard.py
  flexmeasures/utils/app_utils.py
  flexmeasures/utils/config_defaults.py
Labels: UI, Plugin support

#171 Plugin blueprint registration
  documentation/changelog.rst
  documentation/dev/plugins.rst
  flexmeasures/ui/utils/view_utils.py
  flexmeasures/utils/app_utils.py
Labels: Plugin support

#174 Prepare changelog for 0.6.1
  documentation/changelog.rst
Labels: Still Needs Manual Backport

#185 add setting FLEXMEASURES_EXTRA_CSS_PATH & allow plugins to add custom stylesheets to their base template
  documentation/changelog.rst
  documentation/configuration.rst
  documentation/dev/plugins.rst
  flexmeasures/ui/templates/base.html
  flexmeasures/ui/utils/view_utils.py
  flexmeasures/utils/config_defaults.py
Labels: UI, Plugin support

#183 Add util function to drop unchanged beliefs from a BeliefsDataFrame
  flexmeasures/data/models/time_series.py
  flexmeasures/data/services/time_series.py
Labels: Data

#191 Make sure technical info in base template is shown only if available
  flexmeasures/ui/templates/admin/login_user.html
  flexmeasures/ui/templates/base.html
  flexmeasures/utils/app_utils.py
  to_pypi.sh
Labels: UI, Plugin support

#192 update main copy on FlexMeasures' utility
  Readme.md
  documentation/index.rst
  setup.py
Labels: documentation

#193 allow the @task_with_status_report decorator to accept a name to be used in monitoring
  documentation/changelog.rst
  documentation/dev/error-monitoring.rst
  flexmeasures/data/transactional.py
  flexmeasures/utils/coding_utils.py
Labels: CLI
