Repository FlexMeasures/flexmeasures, pull requests merged in 2021-05, with the labels that each got.

#123 Add footer blocks (copyright notice and credits)
  documentation/changelog.rst
  flexmeasures/ui/templates/base.html
Labels: Plugin support, enhancement

#127 Add release date
  documentation/changelog.rst
Labels: Still Needs Manual Backport

#133 pass last_login_at to user crud UI from backend API correctly
  documentation/changelog.rst
  flexmeasures/data/schemas/times.py
  flexmeasures/data/schemas/users.py
  flexmeasures/data/scripts/cli_tasks/data_add.py
  flexmeasures/ui/crud/users.py
  flexmeasures/ui/tests/utils.py
  flexmeasures/ui/utils/view_utils.py
  flexmeasures/utils/tests/test_time_utils.py
  flexmeasures/utils/time_utils.py
Labels: UI, bug

#134 add delimiter and decimal options to dev-add beliefs CLI command
  flexmeasures/data/scripts/cli_tasks/data_add.py
Labels: CLI

#138 Replaced isnan Jinja filter with more versatile isnull filter
  flexmeasures/ui/__init__.py
  flexmeasures/ui/templates/views/portfolio.html
Labels: UI

#81 Issue 6 entity address scheme improvements 2
  Makefile
  documentation/api/change_log.rst
  documentation/api/introduction.rst
  documentation/changelog.rst
  flexmeasures/api/common/schemas/sensors.py
  flexmeasures/api/common/schemas/tests/test_sensors.py
  flexmeasures/api/common/utils/api_utils.py
  flexmeasures/api/common/utils/validators.py
  flexmeasures/api/v1/implementations.py
  flexmeasures/api/v1_1/implementations.py
  flexmeasures/api/v1_1/tests/conftest.py
  flexmeasures/api/v1_1/tests/test_api_v1_1.py
  flexmeasures/api/v1_1/tests/test_api_v1_1_fresh_db.py
  flexmeasures/api/v1_1/tests/utils.py
  flexmeasures/api/v1_2/implementations.py
  flexmeasures/api/v1_3/implementations.py
  flexmeasures/api/v2_0/implementations/sensors.py
  flexmeasures/api/v2_0/tests/test_api_v2_0_sensors.py
  flexmeasures/api/v2_0/tests/test_api_v2_0_sensors_fresh_db.py
  flexmeasures/api/v2_0/tests/utils.py
  flexmeasures/conftest.py
  flexmeasures/data/models/assets.py
  flexmeasures/data/models/markets.py
  flexmeasures/data/models/time_series.py
  flexmeasures/data/models/weather.py
  flexmeasures/data/schemas/tests/test_times.py
  flexmeasures/data/scripts/cli_tasks/data_add.py
  flexmeasures/data/tests/conftest.py
  flexmeasures/ui/templates/crud/assets.html
  flexmeasures/utils/entity_address_utils.py
  flexmeasures/utils/tests/test_entity_address_utils.py
Labels: API, Data

#139 display loaded plugins in footer
  Makefile
  documentation/changelog.rst
  documentation/dev/plugins.rst
  flexmeasures/ui/templates/base.html
  flexmeasures/ui/utils/view_utils.py
  flexmeasures/utils/app_utils.py
Labels: UI
