Repository FlexMeasures/flexmeasures, pull requests merged in 2022-09, with the labels that each got.

#491 Do not resample data of sensors recording instantaneous values
  documentation/changelog.rst
  flexmeasures/data/models/charts/belief_charts.py
  flexmeasures/data/models/generic_assets.py
Labels: bug, Still Needs Manual Backport

#498 Fix for bug introduced in PR #491
  documentation/changelog.rst
  flexmeasures/data/models/charts/belief_charts.py
  flexmeasures/data/models/generic_assets.py
Labels: bug, UI, Still Needs Manual Backport

#497 Fix creation of assets from CLI
  documentation/changelog.rst
  flexmeasures/data/queries/utils.py
  flexmeasures/data/schemas/generic_assets.py
Labels: Still Needs Manual Backport

#463 Add replay button to sensor and asset pages
  documentation/changelog.rst
  flexmeasures/api/dev/sensors.py
  flexmeasures/api/v3_0/assets.py
  flexmeasures/data/models/charts/belief_charts.py
  flexmeasures/data/models/data_sources.py
  flexmeasures/data/models/generic_assets.py
  flexmeasures/data/models/time_series.py
  flexmeasures/ui/static/css/flexmeasures.css
  flexmeasures/ui/static/js/replay-utils.js
  flexmeasures/ui/templates/base.html
  flexmeasures/ui/templates/crud/asset.html
  flexmeasures/ui/templates/views/sensors.html
Labels: UI

#501 Add beliefs with belief timing
  documentation/changelog.rst
  flexmeasures/cli/data_add.py
  requirements/app.in
Labels: Data, CLI
