Repository FlexMeasures/flexmeasures, pull requests merged in 2022-07, with the labels that each got.

#448 Styling user pages
  documentation/changelog.rst
  flexmeasures/ui/static/css/flexmeasures.css
  flexmeasures/ui/templates/admin/logged_in_user.html
  flexmeasures/ui/templates/crud/user.html
  flexmeasures/ui/templates/crud/users.html
  flexmeasures/ui/tests/test_user_crud.py
Labels: UI

#458 Get resampled data
  documentation/api/change_log.rst
  documentation/changelog.rst
  flexmeasures/api/common/schemas/sensor_data.py
  flexmeasures/api/common/schemas/tests/test_sensor_data_schema.py
  flexmeasures/api/dev/sensors.py
  flexmeasures/api/v3_0/sensors.py
  flexmeasures/data/models/time_series.py
Labels: API, Data

#449 Issue 435 display sensor charts on asset page
  documentation/changelog.rst
  flexmeasures/api/dev/__init__.py
  flexmeasures/api/dev/sensors.py
  flexmeasures/api/v3_0/assets.py
  flexmeasures/data/models/charts/belief_charts.py
  flexmeasures/data/models/charts/defaults.py
  flexmeasures/data/models/data_sources.py
  flexmeasures/data/models/generic_assets.py
  flexmeasures/data/models/time_series.py
  flexmeasures/data/schemas/utils.py
  flexmeasures/data/services/sensors.py
  flexmeasures/ui/static/css/flexmeasures.css
  flexmeasures/ui/templates/base.html
  flexmeasures/ui/templates/crud/asset.html
  flexmeasures/ui/templates/views/new_dashboard.html
  flexmeasures/ui/templates/views/sensors.html
  flexmeasures/ui/tests/test_asset_crud.py
Labels: UI

#461 Issue 423 improve dashboard and asset listing for admins
  documentation/changelog.rst
  flexmeasures/api/v3_0/assets.py
  flexmeasures/api/v3_0/tests/test_assets_api.py
  flexmeasures/data/queries/generic_assets.py
  flexmeasures/data/queries/sensors.py
  flexmeasures/data/queries/utils.py
  flexmeasures/data/services/asset_grouping.py
  flexmeasures/ui/__init__.py
  flexmeasures/ui/crud/assets.py
  flexmeasures/ui/static/css/flexmeasures.css
  flexmeasures/ui/templates/crud/assets.html
  flexmeasures/ui/templates/views/new_dashboard.html
  flexmeasures/ui/tests/test_asset_crud.py
  flexmeasures/ui/tests/test_views.py
  flexmeasures/ui/utils/view_utils.py
  flexmeasures/ui/views/new_dashboard.py
Labels: UI

#466 Toy tutorial UI fixes
  documentation/changelog.rst
  flexmeasures/cli/data_add.py
  flexmeasures/data/models/charts/belief_charts.py
  flexmeasures/data/models/data_sources.py
Labels: UI

#459 Adapt formatter for ISO durations
  documentation/changelog.rst
  flexmeasures/api/common/schemas/sensor_data.py
  flexmeasures/api/v1_1/tests/utils.py
  flexmeasures/api/v1_2/implementations.py
  flexmeasures/api/v1_3/implementations.py
  flexmeasures/api/v2_0/tests/utils.py
  flexmeasures/api/v3_0/sensors.py
  flexmeasures/utils/tests/test_time_utils.py
  flexmeasures/utils/time_utils.py
Labels: API

#467 Issue 460 remember selected calendar period within session
  flexmeasures/api/dev/sensors.py
  flexmeasures/api/v3_0/assets.py
  flexmeasures/ui/templates/crud/asset.html
  flexmeasures/ui/templates/views/sensors.html
  flexmeasures/ui/utils/view_utils.py
Labels: UI
