Repository FlexMeasures/flexmeasures, pull requests merged in 2022-01, with the labels that each got.

#307 Sensor charts load most recent beliefs by default
  flexmeasures/data/models/time_series.py
Labels: UI

#310 Fix resolution of bar charts
  documentation/changelog.rst
Labels: Data, UI

#334 Ability to add sensor capacity if they measure power
  flexmeasures/cli/data_add.py
Labels: CLI
