Repository FlexMeasures/flexmeasures, pull requests merged in 2022-04, with the labels that each got.

#412 Prefer conversion to short stock units
  documentation/changelog.rst
  flexmeasures/data/queries/annotations.py
  flexmeasures/utils/tests/test_unit_utils.py
  flexmeasures/utils/unit_utils.py
Labels: Still Needs Manual Backport, Units

#413 Default chart legibility
  documentation/changelog.rst
  flexmeasures/data/models/charts/defaults.py
  flexmeasures/data/tests/test_chart_utils.py
  flexmeasures/ui/static/css/flexmeasures.css
  flexmeasures/ui/templates/views/sensors.html
Labels: UI

#414 Fix search filter and CLI test
  documentation/changelog.rst
  flexmeasures/cli/tests/test_data_show.py
  flexmeasures/data/models/time_series.py
Labels: bug, Still Needs Manual Backport

#415 Upgrade pint==0.19.1
  documentation/changelog.rst
  flexmeasures/utils/tests/test_unit_utils.py
  flexmeasures/utils/unit_utils.py
  requirements/app.in
  requirements/app.txt
Labels: Units

#417 Add high-level architecture to docs & Readme
  Readme.md
  documentation/index.rst
Labels: documentation

#421 Allow passing a tuple of sources
  documentation/changelog.rst
  flexmeasures/data/models/parsing_utils.py
Labels: Data, refactoring

#416 First version of Dockerfile & docker-compose
  .gitignore
  Dockerfile
  Makefile
  Readme.md
  ci/load-psql-extensions.sql
  ci/setup-postgres.sh
  docker-compose.yml
  documentation/changelog.rst
  documentation/conf.py
  documentation/configuration.rst
  documentation/dev/ci.rst
  documentation/dev/docker-compose.rst
  documentation/host/data.rst
  documentation/host/deployment.rst
  documentation/host/docker.rst
  documentation/index.rst
  documentation/tut/installation.rst
  documentation/tut/toy-example-from-scratch.rst
  flexmeasures/api/v3_0/__init__.py
  flexmeasures/api/v3_0/health.py
  flexmeasures/cli/data_add.py
  flexmeasures/data/schemas/sensors.py
  flexmeasures/utils/config_utils.py
  requirements/app.txt
  requirements/docs.in
  requirements/docs.txt
  wsgi.py
Labels: API, Continuous Integration, installation

#424 Except all errors when checking for valid unit
  documentation/changelog.rst
  flexmeasures/utils/tests/test_unit_utils.py
  flexmeasures/utils/unit_utils.py
Labels: bug, Still Needs Manual Backport, Units

#426 Issue 420 dark mode logo in readme
  Readme.md
Labels: documentation
