Repository FlexMeasures/flexmeasures, pull requests merged in 2023-09, with the labels that each got.

#713 CLI smart autocompletion
  Makefile
  flexmeasures/cli/scripts/add_scripts_path.sh
  flexmeasures/cli/scripts/click-complete.bash
  flexmeasures/cli/scripts/click-complete.fish
  flexmeasures/cli/scripts/click-complete.zsh
Labels: enhancement, CLI

#845 Clean up job data source retrieval
  flexmeasures/data/services/scheduling.py
Labels: deprecation, jobs

#844 rename `source` to `sources` and fetch only one value per event
  documentation/changelog.rst
  flexmeasures/data/models/reporting/profit.py
Labels: bug, Reporting

#801 installation: bump piptools to target >=7.2
  Makefile
  requirements/3.10/dev.txt
  requirements/3.10/docs.txt
  requirements/3.10/test.txt
  requirements/3.11/dev.txt
  requirements/3.11/docs.txt
  requirements/3.11/test.txt
  requirements/3.8/dev.txt
  requirements/3.8/docs.txt
  requirements/3.8/test.txt
  requirements/3.9/dev.txt
  requirements/3.9/docs.txt
  requirements/3.9/test.txt
  requirements/dev.in
  requirements/docs.in
  requirements/test.in
Labels: installation, dependency-hygiene

#800 ci: build docker images automatically
  .github/workflows/build.yml
  .github/workflows/generate-dummy-price.sh
  documentation/changelog.rst
Labels: Continuous Integration

#847 ci: update build matrix to target multiple python versions
  .github/workflows/lint-and-test.yml
  documentation/changelog.rst
Labels: Continuous Integration

#843 installation: added docker script to auto update dependencies for all Py versions
  Makefile
  ci/Dockerfile.update
  ci/update-packages.sh
  documentation/changelog.rst
  documentation/dev/dependency-management.rst
  documentation/index.rst
Labels: installation

#852 fix(docs): IDs
  documentation/tut/building_uis.rst
Labels: documentation

#851 Feat/interpolate instantaneous sensor charts
  documentation/changelog.rst
  flexmeasures/cli/data_edit.py
  flexmeasures/data/models/charts/belief_charts.py
  flexmeasures/data/schemas/attributes.py
Labels: Data, UI

#850 expose storage and ems power capacities as flex-model fields
  documentation/api/change_log.rst
  documentation/api/notation.rst
  documentation/changelog.rst
  flexmeasures/api/v3_0/sensors.py
  flexmeasures/api/v3_0/tests/test_sensor_schedules.py
  flexmeasures/api/v3_0/tests/utils.py
  flexmeasures/data/models/planning/storage.py
  flexmeasures/data/models/planning/tests/test_solver.py
  flexmeasures/data/schemas/scheduling/__init__.py
  flexmeasures/data/schemas/scheduling/storage.py
Labels: Scheduling

#856 add headroom charts to tutorial part II
  documentation/changelog.rst
  documentation/tut/toy-example-expanded.rst
  documentation/tut/toy-example-reporter.rst
Labels: documentation

#849 feat: add chart action to export data to CSV
  documentation/changelog.rst
  flexmeasures/ui/static/css/flexmeasures.css
  flexmeasures/ui/static/js/data-utils.js
  flexmeasures/ui/templates/base.html
  flexmeasures/ui/utils/chart_defaults.py
  flexmeasures/ui/utils/view_utils.py
Labels: UI

#838 Upgrade Flask ecosystem dependencies
  .vscode/spellright.dict
  documentation/changelog.rst
  flexmeasures/api/common/implementations.py
  flexmeasures/api/common/schemas/sensor_data.py
  flexmeasures/api/conftest.py
  flexmeasures/api/tests/test_auth_token.py
  flexmeasures/api/tests/test_task_runs.py
  flexmeasures/api/v3_0/accounts.py
  flexmeasures/api/v3_0/assets.py
  flexmeasures/api/v3_0/sensors.py
  flexmeasures/api/v3_0/tests/test_accounts_api.py
  flexmeasures/api/v3_0/tests/test_api_v3_0_users.py
  flexmeasures/api/v3_0/tests/test_api_v3_0_users_fresh_db.py
  flexmeasures/api/v3_0/tests/test_assets_api.py
  flexmeasures/api/v3_0/tests/test_assets_api_fresh_db.py
  flexmeasures/api/v3_0/tests/test_sensor_data.py
  flexmeasures/api/v3_0/tests/test_sensor_data_fresh_db.py
  flexmeasures/api/v3_0/tests/test_sensor_schedules.py
  flexmeasures/api/v3_0/tests/test_sensors_api.py
  flexmeasures/api/v3_0/users.py
  flexmeasures/app.py
  flexmeasures/auth/decorators.py
  flexmeasures/conftest.py
  flexmeasures/ui/crud/users.py
  flexmeasures/ui/static/css/external/rq-dashboard-bootstrap.min.css
  flexmeasures/ui/static/css/flexmeasures.css
  flexmeasures/ui/templates/base.html
  flexmeasures/ui/templates/rq_dashboard/base.html
  flexmeasures/ui/templates/rq_dashboard/dashboard.html
  flexmeasures/ui/utils/view_utils.py
  requirements/3.10/app.txt
  requirements/3.10/dev.txt
  requirements/3.10/docs.txt
  requirements/3.10/test.txt
  requirements/3.11/app.txt
  requirements/3.11/dev.txt
  requirements/3.11/docs.txt
  requirements/3.11/test.txt
  requirements/3.8/app.txt
  requirements/3.8/dev.txt
  requirements/3.8/docs.txt
  requirements/3.8/test.txt
  requirements/3.9/app.txt
  requirements/3.9/dev.txt
  requirements/3.9/docs.txt
  requirements/3.9/test.txt
  requirements/app.in
Labels: dependency-hygiene

#859 save scheduler info into rq job
  documentation/changelog.rst
  flexmeasures/api/common/responses.py
  flexmeasures/api/v3_0/sensors.py
  flexmeasures/data/models/planning/__init__.py
  flexmeasures/data/models/planning/storage.py
  flexmeasures/data/services/scheduling.py
Labels: API, Scheduling

#857 782 update fm modes documentation for sunset of api versions 3
  documentation/changelog.rst
  documentation/configuration.rst
  documentation/host/modes.rst
  flexmeasures/data/services/time_series.py
  flexmeasures/utils/config_defaults.py
Labels: documentation, deprecation

#860 fix: instruct client browser to reload JS
  documentation/changelog.rst
  flexmeasures/ui/templates/base.html
Labels: bug, UI

#861 fix: rq queue name in menu
  flexmeasures/app.py
  flexmeasures/ui/__init__.py
  flexmeasures/ui/static/css/flexmeasures.css
  flexmeasures/ui/templates/base.html
  flexmeasures/ui/utils/view_utils.py
Labels: bug, UI
