Repository FlexMeasures/flexmeasures, pull requests merged in 2024-10, with the labels that each got.

#1204 fix: footer stays at the bottom (not sticky!)
  documentation/changelog.rst
  flexmeasures/ui/templates/base.html
Labels: UI

#1192 Refactor/simplify audit log messages
  flexmeasures/api/v3_0/accounts.py
  flexmeasures/api/v3_0/assets.py
  flexmeasures/api/v3_0/tests/test_assets_api.py
Labels: refactoring

#1205 Uses load_default for all APIs
  flexmeasures/api/v3_0/accounts.py
  flexmeasures/api/v3_0/users.py
Labels: API

#1207 feat: globalize and simplify toasts
  documentation/changelog.rst
  flexmeasures/ui/templates/base.html
  flexmeasures/ui/templates/crud/account.html
Labels: UI

#1208 Sensorstoshow input
  documentation/changelog.rst
  flexmeasures/ui/crud/assets/forms.py
  flexmeasures/ui/templates/crud/asset.html
Labels: UI

#1202 Assets UI pagination
  documentation/changelog.rst
  flexmeasures/api/v3_0/accounts.py
  flexmeasures/api/v3_0/assets.py
  flexmeasures/api/v3_0/users.py
  flexmeasures/ui/crud/accounts.py
  flexmeasures/ui/templates/crud/account.html
  flexmeasures/ui/templates/crud/assets.html
Labels: UI

#1191 feat: search filter on sensor API
  documentation/changelog.rst
  flexmeasures/api/common/schemas/generic_assets.py
  flexmeasures/api/common/schemas/search.py
  flexmeasures/api/common/schemas/sensors.py
  flexmeasures/api/v3_0/accounts.py
  flexmeasures/api/v3_0/assets.py
  flexmeasures/api/v3_0/sensors.py
  flexmeasures/api/v3_0/tests/test_assets_api.py
  flexmeasures/api/v3_0/tests/test_sensors_api.py
  flexmeasures/api/v3_0/users.py
  flexmeasures/data/queries/sensors.py
  flexmeasures/data/services/sensors.py
  flexmeasures/ui/templates/crud/asset.html
Labels: API

#1211 fix: visualize 'forecasting script' data source as just a 'forecaster'
  documentation/changelog.rst
  flexmeasures/data/models/data_sources.py
Labels: bug, UI

#1213 Fix/sensor stats timezone
  documentation/changelog.rst
  flexmeasures/api/v3_0/tests/test_sensors_api.py
  flexmeasures/data/services/sensors.py
  flexmeasures/ui/templates/views/sensors.html
  flexmeasures/utils/config_defaults.py
Labels: UI

#1203 Consistently style button groups
  flexmeasures/ui/static/css/flexmeasures.css
Labels: UI, Plugin support

#1224 fix: docs should build again
  flexmeasures/ui/__init__.py
Labels: bug, documentation

#1226 Fix build pipeline by excluding sphinx==7.4.*
  requirements/3.10/docs.txt
  requirements/3.11/docs.txt
  requirements/3.9/docs.txt
  requirements/docs.in
Labels: bug, documentation

#1220 Display deactivate btn only as admin/account-admin
  documentation/changelog.rst
  flexmeasures/ui/templates/crud/user.html
Labels: bug, UI, multi-tenancy
