Repository FlexMeasures/flexmeasures, pull requests merged in 2024-09, with the labels that each got.

#1163 Feature/rq dashboard sort order
  documentation/changelog.rst
  flexmeasures/ui/templates/base.html
  flexmeasures/ui/templates/rq_dashboard/base.html
  flexmeasures/ui/templates/rq_dashboard/update_links.js
  requirements/3.10/app.txt
  requirements/3.11/app.txt
  requirements/3.8/app.txt
  requirements/3.9/app.txt
  requirements/app.in
Labels: UI, jobs

#1164 Asset search filter applies to both asset names and account names
  documentation/api/change_log.rst
  documentation/changelog.rst
  flexmeasures/api/v3_0/assets.py
Labels: UI

#1169 Asset search filter applies to both asset names and account names
  documentation/api/change_log.rst
  documentation/changelog.rst
  flexmeasures/api/common/schemas/generic_assets.py
  flexmeasures/api/v3_0/assets.py
  flexmeasures/data/queries/generic_assets.py
  flexmeasures/ui/templates/crud/assets.html
Labels: API, UI

#988 Speed up assets and accounts pages
  documentation/api/change_log.rst
  documentation/changelog.rst
  documentation/tut/toy-example-setup.rst
  flexmeasures/api/common/schemas/generic_assets.py
  flexmeasures/api/v3_0/assets.py
  flexmeasures/api/v3_0/tests/test_assets_api.py
  flexmeasures/api/v3_0/users.py
  flexmeasures/data/models/user.py
  flexmeasures/data/queries/generic_assets.py
  flexmeasures/data/schemas/generic_assets.py
  flexmeasures/ui/crud/accounts.py
  flexmeasures/ui/crud/assets/utils.py
  flexmeasures/ui/crud/assets/views.py
  flexmeasures/ui/crud/users.py
  flexmeasures/ui/static/js/flexmeasures.js
  flexmeasures/ui/templates/crud/assets.html
  flexmeasures/ui/tests/conftest.py
  flexmeasures/ui/tests/test_asset_crud.py
  flexmeasures/ui/tests/test_user_crud.py
  flexmeasures/ui/tests/test_views.py
  flexmeasures/ui/tests/utils.py
  flexmeasures/ui/utils/view_utils.py
Labels: API, UI

#1176 Belief chart: legends possible per plot
  documentation/changelog.rst
  flexmeasures/api/v3_0/assets.py
  flexmeasures/data/models/charts/belief_charts.py
  flexmeasures/data/models/generic_assets.py
  flexmeasures/ui/templates/base.html
Labels: UI, Still Needs Changelog Entry, GraphDeliveryImprovements

#1193 Split legends in case of vertically concatenated chart
  documentation/changelog.rst
  flexmeasures/ui/templates/base.html
Labels: UI

#1142 Speed up status page
  documentation/changelog.rst
  flexmeasures/data/services/sensors.py
Labels: enhancement
