Repository FlexMeasures/flexmeasures, pull requests merged in 2024-11, with the labels that each got.

#1219 Search sensors in API by asset
  documentation/changelog.rst
  flexmeasures/api/v3_0/sensors.py
  flexmeasures/api/v3_0/tests/test_sensors_api.py
Labels: API

#1233 Chore/python 3.12
  .github/workflows/lint-and-test.yml
  ci/update-packages.sh
  documentation/changelog.rst
  flexmeasures/data/services/scheduling.py
  flexmeasures/ui/tests/test_assets_forms.py
  requirements/3.12/app.txt
  requirements/3.12/dev.txt
  requirements/3.12/docs.txt
  requirements/3.12/test.txt
  setup.py
Labels: dependency-hygiene

#1236 Add link to account on logged-in-user page
  flexmeasures/ui/templates/admin/logged_in_user.html
Labels: UI

#1238 fix: use of unit and resolution of the output sensor
  documentation/changelog.rst
  flexmeasures/data/models/reporting/pandas_reporter.py
Labels: bug, Still Needs Manual Backport, Reporting

#1239 feat: sort asset table
  documentation/changelog.rst
  flexmeasures/api/v3_0/assets.py
  flexmeasures/api/v3_0/tests/test_assets_api.py
  flexmeasures/ui/templates/crud/assets.html
Labels: API, UI

#1234 feat: `flexmeasures add sensor` no longer requires setting a capacity in MW
  documentation/changelog.rst
  documentation/cli/change_log.rst
  flexmeasures/cli/data_add.py
Labels: CLI

#1248 fix: issue with sorting on accounts table
  documentation/changelog.rst
  flexmeasures/api/v3_0/accounts.py
  flexmeasures/api/v3_0/tests/test_accounts_api.py
  flexmeasures/ui/templates/crud/accounts.html
Labels: bug

#1247 fix: asset search fails when paired with sorting
  documentation/changelog.rst
  flexmeasures/api/v3_0/assets.py
  flexmeasures/data/queries/generic_assets.py
  flexmeasures/ui/templates/crud/account.html
  flexmeasures/ui/templates/crud/assets.html
Labels: bug

#1253 fix: Link to shown user's audit log, not current user
  flexmeasures/ui/templates/crud/user.html
Labels: UI

#1260 Fix assets to display on /assets/owned_by/<account ID> page
  flexmeasures/ui/crud/assets/views.py
  flexmeasures/ui/templates/crud/assets.html
Labels: bug

#1259 Fixed sorting on asset sensors table
  flexmeasures/api/v3_0/assets.py
  flexmeasures/api/v3_0/tests/test_assets_api.py
  flexmeasures/ui/templates/crud/asset.html
Labels: bug, API, UI

#1262 Chore/update repo url
  setup.py
Labels: documentation

#1256 Fix: Filter users by account on account page, correcting API query
  flexmeasures/ui/templates/base.html
  flexmeasures/ui/templates/crud/account.html
  flexmeasures/ui/templates/crud/users.html
Labels: bug

#1257 feat: allow to customize breadcrumbs (using an attribute)
  documentation/changelog.rst
  documentation/plugin/customisation.rst
  flexmeasures/ui/templates/base.html
  flexmeasures/ui/templates/crud/asset.html
  flexmeasures/ui/templates/views/sensors.html
  flexmeasures/ui/utils/breadcrumb_utils.py
Labels: UI, Plugin support

#1261 Fix asset counter on user page after resetting email or (de)activating user
  documentation/changelog.rst
  flexmeasures/ui/crud/users.py
  flexmeasures/ui/tests/test_user_crud.py
Labels: bug, UI
