Repository FlexMeasures/flexmeasures, pull requests merged in 2025-10, with the labels that each got.

#1720 Feat/delete unchanged beliefs within period
  documentation/changelog.rst
  documentation/cli/change_log.rst
  flexmeasures/cli/data_delete.py
Labels: Data, CLI

#1689 Feat/new flexcontext fields
  documentation/changelog.rst
  documentation/features/scheduling.rst
  flexmeasures/data/schemas/scheduling/__init__.py
  flexmeasures/ui/templates/assets/asset_context.html
  flexmeasures/ui/templates/assets/asset_properties.html
  flexmeasures/ui/tests/test_utils.py
  flexmeasures/ui/views/assets/views.py
Labels: Feature

#1721 fix: some audit logs about sensor events were not committed to db correctly
  documentation/changelog.rst
  flexmeasures/api/v3_0/sensors.py
Labels: API

#1730 Fix/UI/belief horizons
  documentation/changelog.rst
  flexmeasures/data/models/generic_assets.py
Labels: bug, UI

#1699 fix: convert charge point sensors values to timestamp on client side
  documentation/changelog.rst
  flexmeasures/data/models/generic_assets.py
  flexmeasures/ui/templates/base.html
Labels: bug, UI

#1738 Fix/UI/floating spinner
  documentation/changelog.rst
  flexmeasures/ui/templates/assets/asset_graph.html
Labels: UI

#1732 Style/asset context
  documentation/changelog.rst
  flexmeasures/ui/templates/_macros.html
  flexmeasures/ui/views/assets/utils.py
Labels: UI
