Repository FlexMeasures/flexmeasures, pull requests merged in 2025-07, with the labels that each got.

#1548 Group statistics by source id instead of source name.
  documentation/changelog.rst
  flexmeasures/api/v3_0/tests/test_sensors_api.py
  flexmeasures/data/services/sensors.py
Labels: Data, UI

#1564 Made TFA optional, updated the documentation and logs for TOTP_SECRETS setup.
  .github/workflows/readthedocs-pr-link.yml
  Makefile
  documentation/changelog.rst
  documentation/configuration.rst
  documentation/host/installation.rst
  flexmeasures/app.py
  flexmeasures/ui/templates/admin/two_factor_verify_code.html
  flexmeasures/utils/app_utils.py
  flexmeasures/utils/config_defaults.py
Labels: security, Auth

#1567 Chore/security upgrades for 0.27.0
  documentation/changelog.rst
  requirements.txt
  requirements/3.10/app.txt
  requirements/3.10/test.txt
  requirements/3.11/app.txt
  requirements/3.11/test.txt
  requirements/3.12/app.txt
  requirements/3.12/test.txt
  requirements/3.9/app.txt
  requirements/3.9/test.txt
Labels: dependency-hygiene

#1569 Fix/3-digit hex colors
  .github/workflows/lint-and-test.yml
  documentation/changelog.rst
  flexmeasures/ui/utils/color_defaults.py
Labels: bug, UI, multi-tenancy

#1598 Chore: Add automated code security analysis
  .github/workflows/codeql.yml
  requirements.txt
Labels: security

#1584 Tutorial/persist postgres database
  .gitignore
  docker-compose.yml
  documentation/changelog.rst
  documentation/dev/docker-compose.rst
  setup.cfg
Labels: documentation

#1597 Feat: Moved the sensor and asset delete buttons below.
  documentation/changelog.rst
  flexmeasures/ui/templates/assets/asset_properties.html
  flexmeasures/ui/templates/sensors/index.html
Labels: UI

#1600 CLI/use inflection
  flexmeasures/cli/data_delete.py
  flexmeasures/cli/jobs.py
Labels: CLI

#974 Docs/mermaid
  documentation/changelog.rst
  documentation/concepts/data-model.rst
  documentation/conf.py
  documentation/index.rst
  documentation/puppeteer-config.json
  requirements/3.10/docs.txt
  requirements/3.11/docs.txt
  requirements/3.12/docs.txt
  requirements/3.8/docs.txt
  requirements/3.9/docs.txt
  requirements/docs.in
Labels: documentation, good first issue

#1613 Chore/future warnings for Marshmallow 4
  documentation/changelog.rst
  flexmeasures/api/v3_0/accounts.py
  flexmeasures/api/v3_0/assets.py
  flexmeasures/api/v3_0/sensors.py
  flexmeasures/api/v3_0/users.py
  flexmeasures/cli/data_add.py
  flexmeasures/data/schemas/account.py
  flexmeasures/data/schemas/generic_assets.py
  flexmeasures/data/schemas/reporting/__init__.py
  flexmeasures/data/schemas/reporting/profit.py
  flexmeasures/data/schemas/scheduling/__init__.py
  flexmeasures/data/schemas/scheduling/storage.py
  flexmeasures/data/schemas/sensors.py
  flexmeasures/data/schemas/users.py
Labels: dependency-hygiene

#1607 make JS code more robust against initial vars not being ready
  flexmeasures/ui/static/js/daterange-utils.js
  flexmeasures/ui/templates/assets/asset_graph.html
  flexmeasures/ui/templates/base.html
Labels: UI

#1602 Feat/cli/run one job
  documentation/changelog.rst
  documentation/cli/commands.rst
  flexmeasures/cli/jobs.py
Labels: Scheduling, CLI

#1511 Feat/default relaxation prices
  documentation/api/change_log.rst
  documentation/changelog.rst
  documentation/features/scheduling.rst
  flexmeasures/data/schemas/scheduling/__init__.py
  flexmeasures/data/schemas/tests/test_scheduling.py
Labels: Scheduling

#1618 Integration of DBFlexmodelSchema(and its custom validators)
  flexmeasures/api/v3_0/assets.py
  flexmeasures/data/schemas/generic_assets.py
  flexmeasures/data/schemas/scheduling/storage.py
  flexmeasures/data/schemas/tests/test_scheduling.py
  flexmeasures/ui/templates/assets/asset_flexmodel.html
Labels: development, refactoring

#1630 Fix/stop registering play blueprint
  documentation/changelog.rst
  flexmeasures/api/__init__.py
Labels: bug, deprecation
