Repository FlexMeasures/flexmeasures, pull requests merged in 2025-09, with the labels that each got.

#1681 fix: use same timezone offsets for start and end
  documentation/changelog.rst
  flexmeasures/data/models/planning/tests/test_storage_utils.py
  flexmeasures/data/models/planning/utils.py
Labels: bug

#1683 Chore: stop using our API internally
  .vscode/spellright.dict
  documentation/api/v3_0.rst
  documentation/changelog.rst
  flexmeasures/api/v3_0/assets.py
  flexmeasures/api/v3_0/users.py
  flexmeasures/data/schemas/generic_assets.py
  flexmeasures/data/services/generic_assets.py
  flexmeasures/data/services/users.py
  flexmeasures/ui/templates/users/user.html
  flexmeasures/ui/tests/test_account_crud.py
  flexmeasures/ui/tests/test_asset_crud.py
  flexmeasures/ui/tests/test_user_crud.py
  flexmeasures/ui/tests/utils.py
  flexmeasures/ui/views/accounts.py
  flexmeasures/ui/views/api_wrapper.py
  flexmeasures/ui/views/assets/__init__.py
  flexmeasures/ui/views/assets/forms.py
  flexmeasures/ui/views/assets/utils.py
  flexmeasures/ui/views/assets/views.py
  flexmeasures/ui/views/users/views.py
Labels: UI

#1717 Dev/reporter with empty data
  documentation/changelog.rst
  flexmeasures/data/models/reporting/pandas_reporter.py
  flexmeasures/data/models/reporting/tests/conftest.py
  flexmeasures/data/models/reporting/tests/test_pandas_reporter.py
  flexmeasures/data/schemas/reporting/pandas_reporter.py
Labels: Reporting

#1429 Addition of Flex-model field to asset
  documentation/changelog.rst
  documentation/features/scheduling.rst
  documentation/views/asset-data.rst
  flexmeasures/api/v3_0/tests/test_sensors_api.py
  flexmeasures/cli/data_add.py
  flexmeasures/data/migrations/versions/5bde9835fbe3_merge.py
  flexmeasures/data/migrations/versions/d914c764fcb7_merge.py
  flexmeasures/data/migrations/versions/f0ee99278f6f_added_flexmodel_to_generic_asset_model.py
  flexmeasures/data/migrations/versions/f5a9e0effa17_merge.py
  flexmeasures/data/models/data_sources.py
  flexmeasures/data/models/generic_assets.py
  flexmeasures/data/models/legacy_migration_utils.py
  flexmeasures/data/models/planning/__init__.py
  flexmeasures/data/models/planning/storage.py
  flexmeasures/data/models/planning/tests/conftest.py
  flexmeasures/data/models/planning/tests/test_solver.py
  flexmeasures/data/models/planning/tests/utils.py
  flexmeasures/data/models/planning/utils.py
  flexmeasures/data/models/time_series.py
  flexmeasures/data/models/validation_utils.py
  flexmeasures/data/schemas/generic_assets.py
  flexmeasures/data/schemas/scheduling/__init__.py
  flexmeasures/data/schemas/scheduling/storage.py
  flexmeasures/data/schemas/tests/conftest.py
  flexmeasures/data/schemas/tests/test_scheduling.py
  flexmeasures/data/services/generic_assets.py
  flexmeasures/data/services/scheduling.py
  flexmeasures/ui/static/css/flexmeasures.css
  flexmeasures/ui/static/js/ui-utils.js
  flexmeasures/ui/templates/assets/asset_context.html
  flexmeasures/ui/templates/assets/asset_properties.html
  flexmeasures/ui/templates/base.html
  flexmeasures/ui/views/assets/views.py
  flexmeasures/utils/time_utils.py
Labels: Data

#1713 Feat: New CLI command for scheduling
  .github/workflows/build.yml
  documentation/changelog.rst
  documentation/cli/change_log.rst
  documentation/cli/commands.rst
  documentation/dev/docker-compose.rst
  documentation/features/scheduling.rst
  documentation/index.rst
  documentation/tut/forecasting_scheduling.rst
  documentation/tut/scripts/run-tutorial-in-docker.sh
  documentation/tut/scripts/run-tutorial2-in-docker.sh
  documentation/tut/scripts/run-tutorial3-in-docker.sh
  documentation/tut/toy-example-expanded.rst
  documentation/tut/toy-example-from-scratch.rst
  documentation/tut/toy-example-process.rst
  flexmeasures/cli/data_add.py
  flexmeasures/cli/utils.py
  flexmeasures/data/models/planning/storage.py
  flexmeasures/ui/templates/assets/asset_context.html
  flexmeasures/ui/templates/assets/asset_properties.html
Labels: Feature
