Repository FlexMeasures/flexmeasures, pull requests merged in 2025-08, with the labels that each got.

#1649 Fix/update daterange in url after 1531
  documentation/changelog.rst
  flexmeasures/ui/templates/assets/asset_graph.html
  flexmeasures/ui/templates/base.html
  flexmeasures/ui/templates/sensors/index.html
Labels: bug, UI

#1655 feat: consolidate filters within FlexMeasures' `TimedBelief.search`
  flexmeasures/data/models/time_series.py
  flexmeasures/data/services/sensors.py
Labels: refactoring

#1660 Fix/multi index concat
  documentation/changelog.rst
  flexmeasures/data/models/generic_assets.py
Labels: bug, UI, Still Needs Manual Backport

#1647 feat: speed up dict representations
  documentation/changelog.rst
  flexmeasures/data/models/charts/belief_charts.py
  flexmeasures/data/models/data_sources.py
  flexmeasures/data/models/generic_assets.py
  flexmeasures/data/models/time_series.py
Labels: UI

#1661 Chore/move speedup fix to v0.27.2
  documentation/changelog.rst
Labels: documentation

#1641 WIP: Optimised JSONification by using mapping instead of apply and some other changes.
  documentation/changelog.rst
  flexmeasures/data/models/generic_assets.py
Labels: Data, UI

#1667 Fix/nan datetimes in url
  documentation/changelog.rst
  flexmeasures/ui/utils/view_utils.py
Labels: bug, UI, Still Needs Manual Backport

#1670 Fix/serialize and deserialize scheduler kwargs kept in `job.meta`
  documentation/changelog.rst
  flexmeasures/data/services/scheduling.py
Labels: UI, jobs

#1636 Fix/editing public assets
  documentation/changelog.rst
  flexmeasures/api/v3_0/tests/test_assets_api.py
  flexmeasures/data/schemas/generic_assets.py
  flexmeasures/ui/tests/test_asset_crud.py
  flexmeasures/ui/tests/test_assets_utils.py
  flexmeasures/ui/views/assets/__init__.py
  flexmeasures/ui/views/assets/utils.py
  flexmeasures/ui/views/assets/views.py
Labels: UI

#1663 Feat: basic asset type support
  documentation/api/change_log.rst
  documentation/changelog.rst
  documentation/concepts/data-model.rst
  documentation/dev/setup-and-guidelines.rst
  documentation/host/data.rst
  documentation/host/installation.rst
  flexmeasures/api/v3_0/__init__.py
  flexmeasures/api/v3_0/assets.py
  flexmeasures/api/v3_0/health.py
  flexmeasures/api/v3_0/tests/test_assets_api.py
  flexmeasures/data/scripts/data_gen.py
Labels: API, Data, CLI, Still Needs Changelog Entry
