Repository FlexMeasures/flexmeasures, pull requests merged in 2025-05, with the labels that each got.

#1464 chore: update docs on sensors to show
  documentation/views/asset-data.rst
Labels: documentation

#1469 fix: Fixed bug where editing asset overrides its flex-context
  documentation/changelog.rst
  flexmeasures/ui/views/assets/forms.py
Labels: bug

#1471 Quick fix for sensors template
  documentation/changelog.rst
  flexmeasures/ui/templates/sensors/index.html
  flexmeasures/ui/views/sensors.py
Labels: bug

#1470 Set the default_asset_view.
  documentation/changelog.rst
  flexmeasures/api/v3_0/assets.py
  flexmeasures/ui/templates/base.html
  flexmeasures/ui/utils/breadcrumb_utils.py
  flexmeasures/ui/utils/view_utils.py
  flexmeasures/ui/views/assets/views.py
Labels: UI

#1483 fix: DetachedInstanceError when writing to audit log
  documentation/changelog.rst
  flexmeasures/data/models/audit_log.py
Labels: Service/Support tooling

#1490 Chore/update timely-beliefs 3.2.0
  documentation/changelog.rst
  requirements/3.10/app.txt
  requirements/3.11/app.txt
  requirements/3.12/app.txt
  requirements/3.8/app.txt
  requirements/3.9/app.txt
  requirements/app.in
Labels: dependency-hygiene

#1497 fix: `infer_datetime_format` is no longer required
  documentation/changelog.rst
  flexmeasures/cli/data_add.py
Labels: deprecation

#1498 Fix/prefer curtailing later rather than later
  documentation/changelog.rst
  flexmeasures/data/models/planning/__init__.py
  flexmeasures/data/models/planning/storage.py
  flexmeasures/data/models/planning/tests/test_solver.py
  flexmeasures/data/models/planning/utils.py
  flexmeasures/data/tests/test_scheduling_simultaneous.py
Labels: bug, Scheduling

#1499 Fix/curtailment preference price too low
  documentation/changelog.rst
  flexmeasures/data/models/planning/storage.py
  flexmeasures/data/models/planning/tests/test_solver.py
Labels: bug, Scheduling

#1465 feat: implement role modification permission checks for users
  documentation/changelog.rst
  flexmeasures/api/v3_0/tests/conftest.py
  flexmeasures/api/v3_0/tests/test_api_v3_0_users.py
  flexmeasures/api/v3_0/tests/test_api_v3_0_users_fresh_db.py
  flexmeasures/api/v3_0/users.py
  flexmeasures/auth/policy.py
  flexmeasures/auth/tests/test_principal_matching.py
  flexmeasures/data/models/user.py
  flexmeasures/data/schemas/users.py
Labels: API, security
